name: License year updater
description: Updates the year in license files
branding:
  icon: calendar
  color: white
inputs:
  files:
    description: Multiline string of license files to update
    required: true
  exclude:
    description: Multiline string of words in author to exclude
    required: false
  no_range:
    description: Only keep last year instead of range of years
    required: false
runs:
  using: composite
  steps:
    - run: python3 "$GITHUB_ACTION_PATH/update.py" -f "${{ inputs.files }}" -e "${{ inputs.exclude }}"
      shell: bash
