name: License year updater
description: Updates the year in license files
branding:
  icon: calendar
  color: white
inputs:
  files:
    description: Multiline string of license files to update
    required: true
runs:
  using: composite
  steps:
    - run: python3 $GITHUB_ACTION_PATH/update.py -f "${{ inputs.files }}"
      shell: bash
