name: License year updater
description: Updates the year in license files
branding:
  icon: calendar
  color: white
inputs:
  files:
    description: Space-separated list of license files to update
    required: true
runs:
  using: composite
  steps:
    - run: python3 update.py ${{ inputs.files }}
      shell: bash
